Citizen.CreateThread( function()
	RequestIpl("vw_casino_main")
	RequestIpl("vw_casino_garage")
	RequestIpl("vw_casino_carpark")
	RequestIpl("vw_casino_penthouse")
	RequestIpl("vw_dlc_casino_door")
	RequestIpl("hei_dlc_casino_door")
	RequestIpl("hei_dlc_windows_casino")
end)

RequestIpl("vw_casino_penthouse")
    interiorID = GetInteriorAtCoords(976.6364, 70.29476, 115.1641)
    if IsValidInterior(interiorID) then
        EnableInteriorProp(interiorID, "casino_manager_default")
        EnableInteriorProp(interiorID, "Set_Pent_Tint_Shell")
        SetInteriorPropColor(interiorID, "Set_Pent_Tint_Shell", 0)
        EnableInteriorProp(interiorID, "vw_vwint02_pent_spax_shell")
        SetInteriorPropColor(interiorID, "vw_vwint02_pent_spax_shell", 0)
        EnableInteriorProp(interiorID, "vw_vwint02_pent_spa_shell")
        SetInteriorPropColor(interiorID, "vw_vwint02_pent_spa_shell", 0)
        EnableInteriorProp(interiorID, "vw_vwint02_pent_sbt_shell")
        SetInteriorPropColor(interiorID, "vw_vwint02_pent_sbt_shell", 0)
        EnableInteriorProp(interiorID, "vw_vwint02_pent_mbt_shell")
        SetInteriorPropColor(interiorID, "vw_vwint02_pent_mbt_shell", 0)
        EnableInteriorProp(interiorID, "vw_vwint02_pent_hal_window")
        EnableInteriorProp(interiorID, "vw_vwint02_pent_mb_window")
        EnableInteriorProp(interiorID, "vw_vwint02_pent_lou_window")
        EnableInteriorProp(interiorID, "vw_vwint02_pent_sb_window")
        EnableInteriorProp(interiorID, "vw_vwint02_pent_din_window")
        EnableInteriorProp(interiorID, "vw_vwint02_pent_bar_window")
        EnableInteriorProp(interiorID, "vw_vwint02_pent_off_window")
        EnableInteriorProp(interiorID, "vw_vwint02_pent_lv_window")		
        EnableInteriorProp(interiorID, "vw_vwint02_pent_ex_window")
        EnableInteriorProp(interiorID, "vw_vwint02_pent_spax_window")
        EnableInteriorProp(interiorID, "vw_vwint02_pent_spa_window")
        RefreshInterior(interiorID)
    end
