export const configTablet = {
  penalCodePrison: [
    {
      id: 1,
      typeCrime: "Ações Fechadas",
      crimes: [
        {
          id: 1,
          description: "Assalto ao Banco Fleeca C/Refém",
          services: 60,
          fine: 15000,
        },
        {
          id: 51,
          description: "Assalto ao Banco Fleeca",
          services: 50,
          fine: 10000,
        },
        {
          id: 52,
          description: "Assalto ao Banco de Paleto",
          services: 50,
          fine: 15000,
        },
        {
          id: 2,
          description: "Assalto ao Banco Central",
          services: 50,
          fine: 15000,
        },
        {
          id: 53,
          description: "Assalto ao Banco Central C/Refém",
          services: 60,
          fine: 20000,
        },
        {
          id: 3,
          description: "Assalta a Loja de Armas (Ammu-nation)",
          services: 15,
          fine: 5000,
        },
        {
          id: 4,
          description: "Assalto a Joalheria",
          services: 40,
          fine: 10000,
        },
        {
          id: 54,
          description: "Assalto a Joalheria C/Refém",
          services: 50,
          fine: 15000,
        },
        {
          id: 5,
          description: "Assalto a Loja de Departamento",
          services: 20,
          fine: 6000,
        },
        {
          id: 6,
          description: "Assalto ao Niobío",
          services: 70,
          fine: 50000,
        },
        {
          id: 7,
          description: "Barbearia",
          services: 15,
          fine: 50000,
        },
        {
          id: 8,
          description: "Assalto ao Mergulhador",
          services: 30,
          fine: 6000,
        },
        {
          id: 8,
          description: "Assalto ao Mergulhador",
          services: 30,
          fine: 6000,
        },
        {
          id: 88,
          description: "Assalto ao Bobcat",
          services: 30,
          fine: 6000,
        },
        {
          id: 87,
          description: "Assalto ao Grapeseed",
          services: 30,
          fine: 6000,
        },
      ],
    },
    {
      id: 2,
      typeCrime: "Infrações de Trânsito",
      crimes: [
        {
          id: 99,
          description: "Condução Perigosa",
          services: 0,
          fine: 3000,
        },
        {
          id: 55,
          description: "Veiculo Irregular",
          services: 0,
          fine: 2000,
        },
        {
          id: 9,
          description: "Alta Velocidade",
          services: 0,
          fine: 6000,
        },
        {
          id: 10,
          description: "Estacionar em Local Proibido",
          services: 0,
          fine: 4000,
        },
        {
          id: 56,
          description: "Pousar em Local Proibido",
          services: 0,
          fine: 10000,
        },
        {
          id: 11,
          description: "Estacionar/Parar na contramão de direção",
          services: 0,
          fine: 3000,
        },
        {
          id: 12,
          description: "Transitar na contra mão",
          services: 0,
          fine: 1000,
        },
        {
          id: 13,
          description: "Usar buzina prolongada e/ou sucessivamente",
          services: 0,
          fine: 1000,
        },
        {
          id: 57,
          description: "Veículo Abandonado",
          services: 0,
          fine: 3000,
        },
        {
          id: 58,
          description: "Bloquear ou Danificar VTR",
          services: 0,
          fine: 5000,
        },
      ],
    },
    {
      id: 3,
      typeCrime: "Crimes Civis",
      crimes: [
        {
          id: 14,
          description: "Tentativa de fuga",
          services: 15,
          fine: 5000,
        },
        {
          id: 15,
          description: "Disputas de corridas ilegais",
          services: 10,
          fine: 2000,
        },
        {
          id: 16,
          description: "Ameaça",
          services: 10,
          fine: 1000,
        },
        {
          id: 17,
          description: "Assédio",
          services: 200,
          fine: 150000,
        },
        {
          id: 18,
          description: "Assalto a Caixa Eletrônico/Registradora",
          services: 10,
          fine: 2000,
        },
        {
          id: 19,
          description: "Calunia, Injúria & Difamação",
          services: 5,
          fine: 5000,
        },
        {
          id: 20,
          description: "Dano ao Patrimônio",
          services: 10,
          fine: 5000,
        },
        {
          id: 23,
          description: "Estelionato",
          services: 20,
          fine: 10000,
        },
        {
          id: 24,
          description: "Falsidade Ideológica",
          services: 20,
          fine: 10000,
        },
        {
          id: 25,
          description: "Falso Testemunho",
          services: 10,
          fine: 20000,
        },
        {
          id: 26,
          description: "Formação de Quadrilha",
          services: 15,
          fine: 5000,
        },
        {
          id: 27,
          description: "Furto",
          services: 5,
          fine: 5000,
        },
        {
          id: 28,
          description: "Homicídio Culposo",
          services: 20,
          fine: 10000,
        },
        {
          id: 29,
          description: "Homicídio a Servidor Público",
          services: 40,
          fine: 30000,
        },
        {
          id: 30,
          description: "Homicídio Doloso",
          services: 30,
          fine: 30000,
        },
        {
          id: 31,
          description: "Porte Ilegal de Armas Leves",
          services: 10,
          fine: 5000,
        },
        {
          id: 32,
          description: "Porte Ilegal de Armas Médias",
          services: 15,
          fine: 10000,
        },
        {
          id: 33,
          description: "Porte Ilegal de Armas Pesadas",
          services: 20,
          fine: 15000,
        },
        {
          id: 34,
          description: "Produtos Ilícitos",
          services: 10,
          fine: 5000,
        },
        {
          id: 35,
          description: "Receptação",
          services: 10,
          fine: 7000,
        },
        {
          id: 36,
          description: "Roubo",
          services: 10,
          fine: 5000,
        },
        {
          id: 37,
          description: "Roubo à residência",
          services: 10,
          fine: 5000,
        },
        {
          id: 39,
          description: "Multas não pagas",
          services: 10,
          fine: 1000,
        },
        {
          id: 40,
          description: "Tentativa de Homicídio",
          services: 10,
          fine: 10000,
        },
        {
          id: 41,
          description: "Tentativa de Homicídio ao Servidor Público",
          services: 30,
          fine: 20000,
        },
        {
          id: 42,
          description: "Tentativa de Suborno",
          services: 10,
          fine: 3000,
        },
        {
          id: 44,
          description: "Tráfico de Munições",
          services: 20,
          fine: 20000,
        },
        {
          id: 45,
          description: "Tráfico de Armas",
          services: 40,
          fine: 25000,
        },
        {
          id: 46,
          description: "Uso de equipamentos Balísticos",
          services: 5,
          fine: 15000,
        },
        {
          id: 47,
          description: "Ocultação facial",
          services: 0,
          fine: 10000,
        },
        {
          id: 48,
          description: "Obstrução de Justiça",
          services: 10,
          fine: 15000,
        },
        {
          id: 49,
          description: "Fuga do Presidio de Segurança Maxima",
          services: 60,
          fine: 50000,
        },
        {
          id: 50,
          description: "Invasão de Área Militar/Resgate em área militar",
          services: 200,
          fine: 50000,
        },
        {
          id: 5555,
          description: "Sequestro de servidor público",
          services: 150,
          fine: 50000,
        },
        {
          id: 555,
          description: "Roubo de algum veiculo militar",
          services: 200,
          fine: 50000,
        },
      ],
    },
  ],
  reductionOptions: [
    {
      value: "primaryDefendant",
      label: "Réu Primário",
      reductionPercentage: 30,
    },
    {
      value: "mirandasRight",
      label: "Não leitura do direito de miranda",
      reductionPercentage: 50,
    },
    { value: "collaboration", label: "Colaboração", reductionPercentage: 20 },
    { value: "notReduction", label: "Sem redução", reductionPercentage: 0 },
  ],
  logoPolice:
    "https://media.discordapp.net/attachments/973002914664701993/1184624454890950707/vibe.gif?ex=662988ff&is=661713ff&hm=79f6abcd28c7f5a3cabc1b0027690c1d51cf1584e5a3f87c50f7b309bf09eb38&=&width=449&height=449",
  graphicMonths: ["Jul", "Ago", "Set", "Out", "Nov", "Dez"],
};
